tk #4521 udp app

diff --git a/.github/workflows/porfolio.yml b/.github/workflows/porfolio.yml
--- a/.github/workflows/porfolio.yml
+++ b/.github/workflows/porfolio.yml
@@ -10,9 +10,8 @@ env:
   python_version: "3.11"
 
 jobs:
-  build:
+  Test:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout code
         uses: actions/checkout@v4
@@ -29,7 +28,21 @@ jobs:
           pip install pytest
 
       - name: Run unit test
-        run: pytest || true   # prevent workflow from failing when no tests yet
+        run: pytest || true   # prevent workflow from failing when no tests yet:
 
-      - name: Build Docker image
-        run: docker build -t rivelino86/portfolio:${{ github.run_number }} .
+  Build:
+      runs-on: ubuntu-latest
+      steps:
+        - name: Build & push Docker image
+          run: docker build -t rivelino86/portfolio-cicd:${{ github.run_number }} .
+  Scan: 
+      runs-on: ubuntu-latest
+      needs: Build
+      steps:
+         - name: Scan Docker image with Trivy
+           uses: aquasecurity/trivy-action@master
+           with:
+              image-ref: 'myimage:latest'
+              format: 'table'
+              exit-code: '1'    # fails pipeline if vulnerabilities found
+              severity: 'HIGH,CRITICAL'
